# Script for generating xspec code
# Takes as input the output from sphvol.tcl and the chosen cylinder-shell we would like to observe.

set filenamein "volumes.out"
set filenameout "fakemekal.xspec"

set fin [open $filenamein r]

# Read out and define parameters
set nshell 2
set temp 1
set density 0.003
set norm 1

close $fin


# Define procedure to write addcomp to models as a function of volume, shell and temperature
# Syntax: addcomp [Model Name:]<new component number> componentName
proc addcomp {nshell temp density norm} {
	set addcompstring "addcomp fakemek:$nshell mekal & $temp & $density & 0.3 & 0.18 & & $norm &"
	return $addcompstring
}
	
set fout [open $filenameout w]

# Write preliminary xspec code

set time [clock format [clock seconds] -format {%Y-%m-%d %H:%M:%S}]
puts $fout "# Script auto-generated by xspecgen.tcl on $time \n"
# Initiate the model
puts $fout "model 1:fakemek mekal & $temp & $density & 0.3 & 0.18 & & $norm & \n"
puts $fout [addcomp $nshell $temp $density $norm]

close $fout